name: flcp
description: A command-line tool that automatically finds, renames, and copies Flutter build files to your desktop using a standardized naming convention.
repository: https://github.com/Taosif7/flcp
version: 1.0.0

environment:
  sdk: '>=2.19.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  pubspec_parse: ^1.3.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

executables:
  flcp:
