name: flcp
description: A sample command-line application with basic argument parsing.
repository: https://github.com/Taosif7/flcp
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  pubspec_parse: ^1.3.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

executables:
  flcp:
